import Foundation

enum PackCopy {
    static let title = "두 사람의 결혼 준비, 한곳에"
    static let startPack = "결혼 팩 시작하기"
    static let startBody = "파트너가 초대를 수락했어요. 이제 두 사람이 결혼 준비 팩을 시작할 수 있어요."
    static let lockedBody = "파트너가 초대를 수락한 뒤에만 결혼 팩을 시작할 수 있어요."
    static let draftBadge = "나만 보임"
    static let agree = "합의"
    static let hold = "다음에 미룸"
    static let reanswer = "다시 답하기"
    static let submit = "이 답변 제출"
    static let previous = "이전 질문"
    static let next = "다음 질문"
    static let noteLabel = "비공개 메모"
    static let noteHint = "메모는 나만 보여요. 서버에만 저장돼요."
    static let privacyRule = "초안과 메모는 나만 보여요. 제출한 답과 합의만 함께 보여요."
    static let waitingPartner = "상대의 제출을 기다리고 있어요."
    static let bothSubmitted = "두 사람의 답이 공개됐어요."
    static let lockBadge = "공개 잠금"
    static let submitBadge = "제출 잠금"
    static let lockHint = "이 스냅샷은 바뀌지 않아요. 다시 답하면 새 비공개 라운드가 열려요."
    static let saved = "서버에 저장됨"
    static let saveFailed = "저장 실패"
    static let retry = "다시 저장"
    static let emptySubmit = "답을 선택한 뒤에 제출할 수 있어요."
    static let agreementPlaceholder = "함께 지킬 원칙이나 다음 행동을 제안해 보세요."
    static let aligned = "ALIGNED"
    static let close = "CLOSE"
    static let discuss = "DISCUSS"
}
