package app.loveme.pack

object PackCopy {
    const val TITLE = "두 사람의 결혼 준비, 한곳에"
    const val START_PACK = "발행 팩 시작하기"
    const val START_BODY = "파트너가 초대를 수락했어요. 이제 두 사람이 결혼 준비 팩을 시작할 수 있어요."
    const val LOCKED_BODY = "파트너가 초대를 수락한 뒤에만 결혼 팩을 시작할 수 있어요."
    const val DRAFT_BADGE = "나만 보임"
    const val AGREE = "합의"
    const val HOLD = "다음에 미룸"
    const val REANSWER = "다시 답하기"
    const val SUBMIT = "이 답변 제출"
    const val PREVIOUS = "이전 질문"
    const val NEXT = "다음 질문"
    const val NOTE_LABEL = "비공개 메모"
    const val NOTE_HINT = "메모는 나만 보여요. 서버에만 저장돼요."
    const val PRIVACY_RULE = "초안과 메모는 나만 보여요. 제출한 답과 합의만 함께 보여요."
    const val WAITING_PARTNER = "상대의 제출을 기다리고 있어요."
    const val BOTH_SUBMITTED = "두 사람의 답이 공개됐어요."
    const val LOCK_BADGE = "공개 잠금"
    const val SUBMIT_BADGE = "제출 잠금"
    const val LOCK_HINT = "이 스냅샷은 바뀌지 않아요. 다시 답하면 새 비공개 라운드가 열려요."
    const val SAVED = "서버에 저장됨"
    const val SAVE_FAILED = "저장 실패"
    const val RETRY = "다시 저장"
    const val EMPTY_SUBMIT = "답을 선택한 뒤에 제출할 수 있어요."
    const val AGREEMENT_PLACEHOLDER = "함께 지킬 원칙이나 다음 행동을 제안해 보세요."
}
