import { cp, mkdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { SITE, siteWith } from "../site/config.js";
import { allPages, indexModel } from "../site/content.js";
import { renderIndex, renderQuestionPage, renderResultPage } from "../site/render.js";
import { questionsFor } from "../src/packs.js";
import { PUBLISHED } from "../site/config.js";
import { pagesFiles, robotsTxt, sitemapXml } from "../site/seo.js";

/**
 * Generates the public question site into `site/dist/`.
 *
 * Separate from `scripts/build.mjs` because the two are separate deployables: the app's API holds
 * couples' private notes and the site wants to be cached by strangers, so they do not belong in
 * one process on one origin. They share this repository, and nothing else.
 *
 * Every page is written as `<slug>/<n>/index.html` so a static host serves it at a trailing-slash
 * URL with no rewrite rules to configure — the cheapest hosting arrangement that still gives clean
 * URLs, which matters because the whole point is being crawled.
 *
 * Run: `AB_SITE_ORIGIN=https://… AB_APP_ORIGIN=https://… node scripts/build-site.mjs`
 * Both origins are optional: without them the pages build and read correctly, they just carry no
 * canonical and the call to action points at `/`. A real deployment should set them.
 */
const OUT = "site/dist";

const site = siteWith({
  origin: String(process.env.AB_SITE_ORIGIN || SITE.origin).replace(/\/$/, ""),
  appOrigin: String(process.env.AB_APP_ORIGIN || "").replace(/\/$/, "")
});

await rm(OUT, { recursive: true, force: true });
await mkdir(OUT, { recursive: true });

await cp("site/site.css", join(OUT, "site.css"));
// The enhancement module and what it imports, served as-is: there is no bundler and no need for
// one — four small ES modules load natively.
for (const module of ["enhance.js", "answers.js", "reflect.js", "result-copy.js"]) {
  await cp(`site/${module}`, join(OUT, module));
}
await cp("src/tokens.css", join(OUT, "tokens.css"));
// The mark and the subsetted faces, generated by `scripts/build-brand-assets.py` and committed.
// `COVERAGE.txt` is the contract `test/brand.test.js` checks and is not served.
await cp("site/brand", join(OUT, "brand"), { recursive: true, filter: (src) => !src.endsWith("COVERAGE.txt") });

await writeFile(join(OUT, "index.html"), renderIndex(indexModel({ site }), site));

const pages = allPages({ site });
for (const model of pages) {
  // model.path is `/slug/` or `/slug/2/`; both become a directory with an index.html in it.
  const dir = join(OUT, model.path.replace(/^\/|\/$/g, ""));
  await mkdir(dir, { recursive: true });
  await writeFile(join(dir, "index.html"), renderQuestionPage(model, site));
}

// One sheet per published pack. It is a shell: the answers are in the reader's browser and have
// never been anywhere else, so there is nothing here to prerender.
for (const entry of PUBLISHED) {
  const questions = questionsFor(entry.packId);
  if (!questions.length) continue;
  const dir = join(OUT, entry.slug, "result");
  await mkdir(dir, { recursive: true });
  await writeFile(join(dir, "index.html"), renderResultPage(entry.slug, questions, site));
}

// The sheet is personal and carries noindex, so it is deliberately absent from the sitemap.
await writeFile(join(OUT, "sitemap.xml"), sitemapXml(pages, site));
await writeFile(join(OUT, "robots.txt"), robotsTxt(site));

// What Pages needs, decided in `pagesFiles` so a test can assert it without reading a build.
for (const [name, body] of Object.entries(pagesFiles(site))) {
  await writeFile(join(OUT, name), body);
}

console.log(`Built AB question site to ${OUT}/ (${pages.length} question page${pages.length === 1 ? "" : "s"})`);
if (!site.origin) console.log("  note: AB_SITE_ORIGIN is unset, so pages carry no canonical URL");
if (!site.appOrigin) console.log("  note: AB_APP_ORIGIN is unset, so the call to action points at /");
