import { definePack } from "./pack-schema.js";

/**
 * The marriage pack's content. Shape, ordering and validation live in `definePack`; the registry
 * that makes it findable alongside future packs lives in `src/packs.js`. This file stays what it
 * has always been — the questions themselves — and keeps exporting `marriagePack` and `questions`
 * so the sixteen modules that import them do not have to change.
 */
export const marriagePack = definePack({
  id: "marriage-preparation", catalogId: "marriage", audience: "couple",
  version: "2026.08-preview.2", locale: "ko-KR", title: "Marriage Preparation Pack", estimatedMinutes: 25, freeQuestionCount: 3,
  sections: [
    { id: "home", title: "함께 사는 집", description: "생활 공간과 역할에 대한 서로의 기대를 발견합니다." },
    { id: "connection", title: "친밀감과 개인 시간", description: "애정을 느끼는 방식과 각자에게 필요한 시간을 확인합니다." },
    { id: "money", title: "돈과 선택", description: "예상 밖의 돈과 공동생활비를 다루는 서로의 기준을 이야기합니다." },
    { id: "family", title: "가족과 경계", description: "원가족과 새로운 가정 사이의 경계와 대응 원칙을 이야기합니다." },
    { id: "conflict", title: "갈등과 회복", description: "갈등 뒤 필요한 거리와 연결 방식을 확인합니다." },
    { id: "future", title: "미래의 선택", description: "예상하기 어려운 변화 앞에서 함께 결정하는 방식을 살펴봅니다." }
  ],
  questions: [
    { id: "home-01", sectionId: "home", number: 1, title: "우리에게 집은 어떤 의미에 가장 가까울까요?", intent: "함께 살 공간에 서로 다른 기대가 있는지 알아보는 질문이에요.", example: "예: 특별한 일정이 없는 평범한 저녁에 집에서 가장 편안했던 모습을 떠올려 보세요.", whyItMatters: "같은 집에 살아도 서로 다른 활동과 분위기를 기대할 수 있습니다. 어느 방식이 더 옳은지를 정하기보다, 공간을 사용할 때 서로 배려해야 할 기대를 미리 발견하는 것이 목적입니다.", researchKeywords: ["주거 기대", "생활 경계", "공동생활"], choices: [{id:"home-rest",label:"외부의 피로를 회복하는 조용한 안식처"},{id:"home-social",label:"가족과 친구가 자연스럽게 모이는 열린 공간"},{id:"home-independent",label:"각자의 생활과 취향을 존중하는 독립적인 공간"},{id:"home-growth",label:"함께 목표를 세우고 성장해 가는 생활의 기반"}] },
    { id: "money-01", sectionId: "money", number: 2, title: "예상하지 못한 여유 자금이 생기면 어떻게 하고 싶나요?", intent: "같은 여유 자금을 서로 어떻게 바라보는지 발견하는 질문이에요.", example: "예: 공동생활에 쓸 수 있는 보너스 300만 원이 생겼다고 상상해 보세요.", whyItMatters: "돈을 쓰고 보관하는 방식에는 서로 다른 생활 경험과 기대가 반영됩니다. 선택을 평가하기보다 두 사람이 돈에서 무엇을 중요하게 여기는지 이해하는 대화가 중요합니다.", researchKeywords: ["재정 가치관", "가계 자금 배분", "공동 의사결정"], choices: [{id:"money-save",label:"대부분 비상금이나 예비 생활비로 남긴다"},{id:"money-experience",label:"대부분 여행이나 취미 같은 공동 경험에 사용한다"},{id:"money-growth",label:"대부분 주거·투자·교육 같은 장기 계획에 사용한다"},{id:"money-split",label:"대부분 두 사람의 개인 자유 지출 몫으로 똑같이 나눈다"}] },
    { id: "conflict-01", sectionId: "conflict", number: 3, title: "감정이 크게 상한 직후, 가장 먼저 필요한 것은 무엇인가요?", intent: "갈등 직후 서로에게 기대하는 첫 회복 행동을 확인하는 질문이에요.", example: "예: 말다툼이 끝났지만 아직 마음이 가라앉지 않은 상황을 떠올려 보세요.", whyItMatters: "갈등 뒤 서로에게 필요한 거리와 연결 방식이 다를 수 있습니다. 차이를 애정의 크기로 해석하지 않고, 먼저 필요한 행동을 이해하는 것이 목적입니다.", researchKeywords: ["갈등 회복", "정서 조절", "재접근 신호"], choices: [{id:"conflict-space",label:"혼자 생각하며 진정할 수 있는 시간"},{id:"conflict-empathy",label:"판단이나 해결책 없이 감정을 들어주는 대화"},{id:"conflict-talk",label:"무엇이 문제였는지 정리하는 대화"},{id:"conflict-routine",label:"평범한 일상을 함께하며 긴장을 낮추는 시간"}] },
    { id: "home-02", sectionId: "home", number: 4, title: "두 사람 모두 지친 날, 밀린 집안일에 가장 먼저 어떻게 대응하고 싶나요?", intent: "여유가 부족한 날에도 사용할 수 있는 예외 상황의 기본 대응을 찾아보는 질문이에요.", example: "예: 퇴근이 늦었는데 설거지와 빨래가 모두 남아 있는 평일 밤을 떠올려 보세요.", whyItMatters: "집안일의 양보다 생활 기준을 낮출 수 있는 범위가 달라 부담이 되기도 합니다. 지친 상황에서 적용할 첫 대응을 미리 이야기하면 매번 책임을 협상해야 하는 피로를 줄일 수 있습니다.", researchKeywords: ["가사 분담", "인지 노동", "상황 대응"], choices: [{id:"home02-maintain",label:"평소 기준을 유지하도록 지금 할 일을 나눈다"},{id:"home02-essential",label:"식사와 위생처럼 필수적인 일만 함께 정한다"},{id:"home02-schedule",label:"오늘은 미루고 함께 처리할 날짜부터 정한다"},{id:"home02-help",label:"배달·세탁·청소 같은 외부 도움을 먼저 검토한다"}] },
    { id: "money-02", sectionId: "money", number: 5, title: "매달 공동생활비를 내고 남은 돈은 어떤 원칙으로 관리하고 싶나요?", intent: "공동의 목표와 각자의 경제적 자율성 사이에서 편안한 기본값을 찾는 질문이에요.", example: "예: 월세·식비·공과금을 모두 낸 뒤 각자에게 여유 자금이 남은 달을 생각해 보세요.", whyItMatters: "공동생활을 하면서도 각자가 자유롭게 결정할 수 있는 범위에 대한 기대는 다를 수 있습니다. 금액보다 먼저 기본 원칙과 서로 알려야 하는 범위를 합의하는 것이 목적입니다.", researchKeywords: ["재정 자율성", "공동 예산", "재정 투명성"], choices: [{id:"money02-shared",label:"남은 돈도 대부분 공동 목표를 위해 함께 관리한다"},{id:"money02-ratio",label:"정한 비율만 추가로 모으고 나머지는 각자 관리한다"},{id:"money02-allowance",label:"같은 금액의 개인 사용 몫을 먼저 나눈다"},{id:"money02-independent",label:"공동생활비 이후의 돈은 각자 관리한다"}] },
    { id: "conflict-02", sectionId: "conflict", number: 6, title: "의견 충돌로 대화를 멈췄다면 언제 다시 이야기하는 것이 편안한가요?", intent: "대화를 다시 시작할 시간 범위를 서로 예측할 수 있게 만드는 질문이에요.", example: "예: 목소리가 높아져 잠시 대화를 중단하기로 한 상황을 떠올려 보세요.", whyItMatters: "한 사람에게 침묵은 진정할 시간이고 다른 사람에게는 관계가 끊긴 신호처럼 느껴질 수 있습니다. 서로 다른 시간 감각을 알면 재촉이나 회피로 오해하는 일을 줄일 수 있습니다.", researchKeywords: ["갈등 중단", "재대화", "예측 가능성"], choices: [{id:"conflict02-soon",label:"30분 이내에 다시 이야기한다"},{id:"conflict02-today",label:"30분은 쉬되 그날 안에 다시 이야기한다"},{id:"conflict02-tomorrow",label:"다음 날 정한 시간에 다시 이야기한다"},{id:"conflict02-later",label:"이틀 이상 충분한 시간을 가진 뒤 다시 이야기한다"}] },
    { id: "family-01", sectionId: "family", number: 7, title: "명절 당일 양가 일정이 겹친다면 어떤 기본 원칙을 선호하나요?", intent: "행사 때마다 처음부터 협상하지 않아도 되는 배분 기준을 찾아보는 질문이에요.", example: "예: 같은 날 양가에서 모두 방문해 달라고 요청했고 두 곳을 충분히 방문하기는 어려운 상황입니다.", whyItMatters: "가족 행사는 시간 배분뿐 아니라 소속감과 의무에 대한 기대가 함께 드러나는 경우가 있습니다. 특정 가족의 우열을 정하기보다 두 사람이 납득할 기본 규칙을 확인하는 것이 목적입니다.", researchKeywords: ["원가족 경계", "명절 의사결정", "공정성"], choices: [{id:"family01-alternate",label:"해마다 방문할 가족을 번갈아 정한다"},{id:"family01-split",label:"시간을 나누어 같은 날 양가를 모두 방문한다"},{id:"family01-separate",label:"각자 자신의 가족을 따로 방문한다"},{id:"family01-context",label:"거리·건강·행사 상황을 보고 한 가족을 정한다"}] },
    { id: "family-02", sectionId: "family", number: 8, title: "두 사람 사이의 일상적인 갈등을 가까운 사람에게 어디까지 이야기해도 괜찮을까요?", intent: "감정을 정리할 자유와 관계의 사생활 사이에서 편안한 경계를 확인하는 질문이에요.", example: "예: 의견이 달랐던 날 친한 친구가 무슨 일이 있었는지 물어본 상황을 떠올려 보세요.", whyItMatters: "누군가에게 이야기하는 것이 한 사람에게는 생각을 정리하는 방법이고, 다른 사람에게는 사생활 공개로 느껴질 수 있습니다. 외부 대화 자체를 평가하기보다 두 사람이 안심할 수 있는 공개 범위를 정하는 것이 목적입니다.", researchKeywords: ["사생활 경계", "자기 개방", "관계 정보 관리"], choices: [{id:"family02-none",label:"상대의 동의 없이는 갈등 내용을 이야기하지 않는다"},{id:"family02-feeling",label:"구체적인 상황은 빼고 내 감정만 이야기한다"},{id:"family02-trusted",label:"미리 합의한 신뢰하는 한 사람에게만 구체적으로 이야기한다"},{id:"family02-own",label:"각자가 직접 경험한 일은 각자의 판단으로 이야기한다"}] },
    { id: "future-01", sectionId: "future", number: 9, title: "한 사람에게 먼 지역의 좋은 일자리 제안이 온다면 무엇을 가장 먼저 평가하고 싶나요?", intent: "큰 기회와 공동생활의 변화를 함께 평가할 첫 기준을 살펴보는 질문이에요.", example: "예: 경력에는 도움이 되지만 이사와 생활 변화가 필요한 제안을 상상해 보세요.", whyItMatters: "같은 기회도 두 사람의 일과 생활에 서로 다른 영향을 줄 수 있습니다. 찬반을 미리 정하기보다 결정 과정에서 먼저 확인하고 싶은 기준을 발견하는 것이 목적입니다.", researchKeywords: ["경력 전환", "공동 결정", "생활 전환"], choices: [{id:"future01-opportunity",label:"제안을 받은 사람의 경력에 주는 기회"},{id:"future01-partner",label:"파트너의 일과 일상에 생기는 변화"},{id:"future01-household",label:"두 사람의 주거와 재정에 미치는 영향"},{id:"future01-reversible",label:"선택을 나중에 되돌리거나 조정할 가능성"}] },
    { id: "future-02", sectionId: "future", number: 10, title: "자녀에 관한 생각이 아직 확실하지 않다면 어떤 재논의 규칙이 편안한가요?", intent: "결론을 재촉하지 않으면서 중요한 주제를 놓치지 않을 확인 방식을 정하는 질문이에요.", example: "예: 지금은 답이 다르거나 한 사람에게 아직 명확한 답이 없는 경우를 떠올려 보세요.", whyItMatters: "자녀에 관한 생각은 시간과 경험에 따라 달라질 수 있습니다. 답을 강요하거나 의학적 가능성을 추정하지 않고, 현재 생각을 다시 확인할 기본 규칙을 나누는 질문입니다.", researchKeywords: ["가족 계획", "의사결정 시기", "기대 조율"], choices: [{id:"future02-once",label:"가까운 시일의 날짜를 한 번 정해 다시 이야기한다"},{id:"future02-quarterly",label:"3개월마다 정기적으로 생각을 확인한다"},{id:"future02-milestone",label:"주거·재정 같은 큰 조건이 바뀔 때만 다시 이야기한다"},{id:"future02-unscheduled",label:"정기 일정 없이 생각이 달라진 사람이 요청할 때 이야기한다"}] },
    { id: "connection-01", sectionId: "connection", number: 11, title: "유난히 지친 한 주가 끝났을 때 어떤 순간에 가장 연결되어 있다고 느끼나요?", intent: "힘을 회복하면서 애정을 체감하는 방식을 서로 알아보는 질문이에요.", example: "예: 둘 다 바빴고 주말에 겨우 함께 시간을 보내게 된 상황을 떠올려 보세요.", whyItMatters: "애정을 표현해도 상대가 기대한 방식과 다르면 노력 자체를 알아보기 어려울 수 있습니다. 한 가지 방식이 더 좋은 것이 아니라, 지친 때 특히 도움이 되는 연결 방식을 구체적으로 나누는 질문입니다.", researchKeywords: ["애정 표현", "정서적 연결", "관계 의식"], choices: [{id:"connection01-talk",label:"방해 없이 서로의 한 주를 들어주는 대화"},{id:"connection01-touch",label:"포옹이나 손잡기 같은 편안한 신체적 친밀감"},{id:"connection01-care",label:"식사나 집안일을 챙겨주는 실질적인 배려"},{id:"connection01-activity",label:"산책이나 취미처럼 함께하는 집중된 시간"}] },
    { id: "connection-02", sectionId: "connection", number: 12, title: "특별한 일정이 없는 주말, 함께하는 시간과 개인 시간을 어느 정도로 나누고 싶나요?", intent: "가까움과 독립성을 모두 지키는 주말의 기본 비율을 찾아보는 질문이에요.", example: "예: 토요일과 일요일 모두 약속이 없는 주말을 떠올려 보세요.", whyItMatters: "함께 있고 싶은 마음과 혼자 회복하고 싶은 필요는 동시에 존재할 수 있습니다. 개인 시간을 거절이나 무관심으로 오해하지 않도록 서로 편안한 기본 비율을 확인하는 것이 목적입니다.", researchKeywords: ["개인 시간", "관계 자율성", "공동 여가"], choices: [{id:"connection02-all",label:"거의 모든 시간을 함께 보낸다"},{id:"connection02-more-together",label:"함께하는 시간을 개인 시간보다 더 많이 둔다"},{id:"connection02-even",label:"함께하는 시간과 개인 시간을 비슷하게 나눈다"},{id:"connection02-more-separate",label:"개인 시간을 함께하는 시간보다 더 많이 둔다"}] }
  ]
});

/** The same list `definePack` derived, kept as a named export for every existing caller. */
export const questions = marriagePack.orderedQuestions;
